### ISSUE TITLE
Add an 'à propos' and a 'nous contacter' in the footer(?) explaining how the adventure started.

### ISSUE THREAD

**Issue by PEmmaD** [rafaelmillan/sosfood#85]

**Comment by xuanbichmai** [comment]
A Propos | Equipe | Mention Legal | Version?

**Comment by rafaelmillan** [comment]
On peut mettre le crédit ici aussi (issue #73)

**Comment by xuanbichmai** [comment]
@PEmmaD : A Propos & Mention Legal
@xuanbichmai: Partenaire | Equipe | Version (Beta) | Nous Contacter
